version: 2

workflows:
  version: 2
  build:
    jobs: [
    {'build': {'context': 'k9-dev-ci'}}
    ]

terraform: &terraform
  docker:
    - image: qualimente/terraform-infra-dev:0.11.14
  working_directory: /module

jobs:
  build:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: add github.com to ~/.ssh/known_hosts
          command: mkdir -p ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: make infra
          command: make all
      - store_artifacts:
          path: /module/.kitchen/
      - run:
          name: destroy minimal test infra
          command: make destroy
